runtime: python37

env_variables:
  BUCKET_NAME: "blurb-blocks-data"
  SEED_LENGTH: "64"
  TEMPERATURE: "0.8"

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

instance_class: B8
manual_scaling:
  instances: 1