runtime: python37

entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 1 --threads 1

instance_class: B8
manual_scaling:
  instances: 1


env_variables:
  BUCKET_NAME: "blurb-blocks"
  SEED_LENGTH: "64"
  TEMPERATURE: "0.8"

handlers:
- url: /.*
  secure: always
  script: auto

