version: '2.3'
services:
  traefik:
    image: traefik
    restart: always
    command: --web --docker --docker.domain=docker.localhost --docker.watch \
      --logLevel=DEBUG \
      --docker.exposedbydefault=false \
      --entryPoints='Name:http Address::80' \
      --defaultEntryPoints='http'
    networks:
      - default
    ports:
      - "80:80"
      - "8085:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  blurbs-server:
    restart: always
    image: asia.gcr.io/cl-syd-ml-writers/ml-api
    environment:
      - BUCKET_NAME=blurb-blocks
      - TEMPERATURE=0.9
    networks:
      - default
    ports:
      - "8000:8000"
    entrypoint:
      - gunicorn
      - -b
      - 0.0.0.0:8000
      - main:app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=machine-blurb"
      - "traefik.frontend.rule=PathPrefixStrip:/blurb"

  life-server:
    restart: always
    image: asia.gcr.io/cl-syd-ml-writers/ml-api
    environment:
      - BUCKET_NAME=this-is-your-life
      - TEMPERATURE=0.9
    networks:
      - default
    ports:
      - "8001:8000"
    entrypoint:
      - gunicorn
      - -b
      - 0.0.0.0:8000
      - main:app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=machine-life"
      - "traefik.frontend.rule=PathPrefixStrip:/life"

  chat-server:
    restart: always
    image: asia.gcr.io/cl-syd-ml-writers/ml-api
    environment:
      - BUCKET_NAME=stacked-qa
      - TEMPERATURE=0.9
    networks:
      - default
    ports:
      - "8002:8000"
    entrypoint:
      - gunicorn
      - -b
      - 0.0.0.0:8000
      - main:app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=machine-chat"
      - "traefik.frontend.rule=PathPrefixStrip:/chat"